---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.1.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

```{python}
import numpy as np
import matplotlib.pyplot as plt
import scipy                  # http://scipy.org/
from scipy import signal

from IPython.display import Image  
# %matplotlib inline
params = {'legend.fontsize': 24,
          'figure.figsize': (12, 8),
         'axes.labelsize': 24,
         'axes.titlesize': 24,
         'xtick.labelsize':24,
         'ytick.labelsize':24}
plt.rcParams.update(params) 



from IPython.display import Image

Image(filename= "fig/eje1.png",width=450)
```

<!-- #region -->
En la figura se muestra un circuitos de adaptación realizado con un inductor y un capacitor. El inductor tiene un $Q_{oL} = 100$ y el capacitor tiene $ESR= 1\Omega$. La fuente tiene una $P_{disp} = 10nW$ a $100MHz$.




1. Calcule $L_1$, $C_1$ y $Q_c$ del circuito resultante para adaptar MTEcte la carga y el generador a $100MHz$ mediante conversiones serie-paralelo. (10ptos)
2. Verificar usando la carta de Smith.(10ptos)
3. Calcule la potencia entregada por la fuente, la potencia en la carga y verificar usando simuladores. (10ptos)
<!-- #endregion -->

```{python}

```

# Comentarios

Este ejercicio plantea resolver un adaptador muy simple, un LC donde ambos componentes presentan perdidas. 

Las conversiones serie/paralelo facilitan encontrar los valores de los componentes del adaptador, donde llevamos el adaptador a un circuito RLC serie o paralelo según convenga. 

Para conocer la respuesta del circuito necesitamos estudiar su respuesta en frecuencia, ya que el modelo final RLC serie o paralelo no tiene la misma respuesta que el circuto practico dado diferencia en la topología. 

En esta hoja de calculo se resolvera el circuito suponiendo que los componentes L y C no presentan perdidas. Luego se analizará la respuesta del circuito en tres condiciones: 

    1. RL, C1s (puramente serie)   
    2. RL en paralelo con C1 sin perdidas
    3. RL en paralelo con C1 con perdidas
    4. Recalculando L1 para la condición de C1 con perdidas.




Los gráficos mostrados en la hoja de calculo se muestean en dBm:  $ 10\cdot log_{10}(\frac{P}{10^{-3}))$. 

Las tensiones y corrientes calculadas estan en valores picos. 

Las potencias en valores eficaces.

# NOTA!!:Los gráficos en LTSpice se muestran dB se realizan con la conversión $ 20\cdot log_{10}(f(x))$ , por lo tanto para encotrar el ancho de banda de $-3dB$ hay que buscar los $-6dB$. No significa que el ancho de banda en potencia sea de $-6dB$.




```{python}
# Datos
QoL = 100
ESR = 1
zg = 10  
Pdisp  = 10e-9 # W RMS
RL  = 100
 
fo  =  100e6
wo = 2*np.pi*fo


# Calculo la impedancia de la fuente para el modelo paralelo
rg = zg.real 



Ptot   = 2 * Pdisp
vg     = (Ptot* (2*rg) *2)**(1/2) # 
print('rg =  {:1.1f} ohms'.format(rg) )
print('vg =  {:1.2e} V'.format(vg) )

```

# Primero vamos a resolver suponiendo que no hay perdidas en el capacitor pero teniendo en cuenta las perdidas del inductor. 
### Conversión paralelo serie del capacitor C1 con RL

```{python}
# conversión RL a RLs, para máxima transferencia de energía a Q constante 
# RL = rg (no se tiene en cuenta las perdidas de adaptador) 
RLp = 100.
RLs = 10. 

# Calculo del Qm (Q matching)
# RLp =  RLs *(1 + Qm**2)
Qm = (RLp/RLs - 1)**(1/2)

# con el Qm es posible calcular C1
#Qm = RLp * wo * C1
C1 = Qm / (RLp * wo)

# Calculo del capacitor resultante serie
C1p  = C1

# Xcs =  Xcp /(1 + 1/Qm**2)
#  1/(wo*C1s) =  (1/(wo*C1p)) /(1 + 1/Qm**2)
#  C1p =  C1s /(1 + 1/Qm**2)
C1s =  C1p *(1 + 1/Qm**2)

# En el modelo serie L sintoniza a C1s
L1 = 1/(wo**2 * C1s)
#  calculo la resistencia de perdida serie del inductor
rpls = (wo*L1)/QoL


# 1/Qc = 1/QoL  + Rext/(wo*L) # Rext = 10 + 10 = 20
Rext = rg + RLs
Qc = 1/((1/QoL)  + (Rext/(wo*L1)) )

BW = fo/Qc

print('Qm  =  {:1.1f} '.format(Qm) )
print('C1  =  {:1.4e} F'.format(C1p) )
print('C1s =  {:1.3e} F'.format(C1s) )
print('L1  =  {:1.4e} Hy'.format(L1) )
print('rpls  =  {:1.3f} ohm'.format(rpls) )
print('Qc  =  {:1.3e} '.format(Qc) )
print('BW  =  {:1.3f} MHz'.format(BW/1e6) )

```

# Simulación y calculos del RLC serie resultante, C1 en serie y sin perdidas. 

```{python}
# Simulando y verificando el circuito serie
# Se mide la potencia en RL (ancho de banda de 6dB)
Image(filename= "fig/eje1sim1.png",width=750)

```

```{python}
# Ahora calculando en la hoja de calculo 
# Defino el array de frecuencia
f =  np.arange(10e6,200e6,.1e6)
# armo el array de w
w = 2*np.pi*f
```

```{python}
## simulando el circuito RLC totalmente SERIE!

## DATOS
print('Los datos empleados para los calculos:')
print('RLs  =  {:1.3f} ohm'.format(RLs) )
print('C1s =  {:1.3e} F'.format(C1s) )
print('L1  =  {:1.4e} Hy'.format(L1) )
print('rpls  =  {:1.3f} ohm'.format(rpls) )
print('rg  =  {:1.3f} ohm'.format(rg) )
print('vg  =  {:1.3e} Vp'.format(vg) )
print('')



# Capacitor serie 
Xcs  = -1/(w*C1s)
ZC   = 1j*Xcs
# inductor serie
Xls  = w*L1
ZL   = rpls + 1j*Xls

# impedancia total que carga a la fuente incluida su impedancia interna
Z   = rg + ZL + ZC + RLs
#plt.plot(f,Z.imag)
#plt.show()


# Potenicia en la carga
i   = vg /Z
vrl = i * RLs
irl = i
Prl = np.abs(irl*vrl)/2 # valor eficaz

imprimePRL(Prl)
```

# Calculos del RLC, pero con C1 en derivación y sin perdidas. 

```{python}
# Simulando y verificando el circuito serie con derivación 
Image(filename= "fig/eje1sim2.png",width=750)
```

```{python}
# Ahora comparamos con el circuito usando el capacitor sin perdidas
## DATOS
print('Los datos empleados para los calculos:')
print('RL  =  {:1.1f} ohm'.format(RL) )
print('C1 =  {:1.3e} F'.format(C1) )


print('L1  =  {:1.4e} Hy'.format(L1) )
print('rpls  =  {:1.3f} ohm'.format(rpls) )
print('rg  =  {:1.3f} ohm'.format(rg) )
print('vg  =  {:1.3e} Vp'.format(vg) )
print('')

# Capacitor serie 
Xcs  = -1/(w*C1)
Zc   = 1j*Xcs

# C1 sin perdidas en paralelo con RL
ZcRL = RL * Zc / (RL +  Zc)

# inductor serie con perdidas
Xls  = w*L1
ZL   = rpls + 1j*Xls


# Impedancia total incluida la impedancia del generador
Z   = rg + ZL + ZcRL

# Calculo de la potenicia de RL
i   = vg /Z
vrl = i * ZcRL
irl = vrl/RL
Prl = np.abs(irl*vrl)/2 # potenica eficaz

imprimePRL(Prl)
```

# Comentario
El ancho de banda es mayor debido a que la definición de Qc es valida para circuitos puramente serie o paralelos. 


# Calculos del RLC, pero con C1 en derivación y con perdidas. 

```{python}
# Simulando y verificando el circuito serie con derivación y las perdidas del capacitor
Image(filename= "fig/eje1sim3.png",width=750)
```

```{python}
# Ahora comparamos con el circuito usando el capacitor con perdidas
## DATOS
print('Los datos empleados para los calculos:')
print('RL  =  {:1.1f} ohm'.format(RL) )
print('C1 =  {:1.3e} F'.format(C1) )
print('ESR  =  {:1.3f} ohm'.format(ESR) )


print('L1  =  {:1.4e} Hy'.format(L1) )
print('rpls  =  {:1.3f} ohm'.format(rpls) )
print('rg  =  {:1.3f} ohm'.format(rg) )
print('vg  =  {:1.3e} Vp'.format(vg) )
print('')

# Capacitor serie 
Xcs  = -1/(w*C1)
Zc   =  ESR +  1j*Xcs

# C1 sin perdidas en paralelo con RL
ZcRL = RL * Zc / (RL +  Zc)

# inductor serie con perdidas
Xls  = w*L1
ZL   = rpls + 1j*Xls


# Impedancia total incluida la impedancia del generador
Z   = rg + ZL + ZcRL

# Calculo de la potenicia de RL
i   = vg /Z
vrl = i * ZcRL
irl = vrl/RL
Prl = np.abs(irl*vrl)/2 # potenica eficaz

imprimePRL(Prl)
```

# Comentario
Si ahora se incluye las perdidas del capacitor C1 con los valores calculados. Se observa que la frecuencia de resonancia ya no es la de proyecto. 

Se calculará a continuación el nuevo valor del inductor. 


# Reaculculando L1 con C1 con perdidas

```{python}
# Calculos
## DATOS
print('Los datos empleados para los calculos:')
print('RL  =  {:1.1f} ohm'.format(RL) )
print('C1 =  {:1.3e} F'.format(C1) )
print('QoL =  {:1.1f} '.format(QoL) )
print('rg  =  {:1.3f} ohm'.format(rg) )
print('vg  =  {:1.3e} Vp'.format(vg) )
print('')

# Capacitor serie 
Xcs  = -1/(wo*C1)
Zc   =  ESR +  1j*Xcs
Qoc  = -Xcs*ESR   
rpcp = ESR*(1+Qoc**2)

# Calculando el paralelo
ZcRL = Zc * RLp / (Zc + RLp)

# De la impedancia resultante calculo Xc
Xc  = -ZcRL.imag
# Calculando las perididas del adaptador
rt =  ZcRL.real
rpcs = rt - RLs
# El Qoc
QoC = Xc*rpcs

# El inductor que sintoniza Xc
Xl  = Xc
L1  = Xl/wo

# Calculando las perdidas
# QoL = Xl/rpls
rpls = Xl/QoL
ZL = rpls + 1j*Xl

# Rext de un circuito serie
Rext = rg + RLs
# Caculando el Qc
# 1/Qc = 1/QoL + 1/QoC + rext/(w*L1)
Qc = 1/(1/QoL + 1/QoC + Rext/(wo*L1))

BW = fo/Qc
print('')
print('Resultado')

print('C1  =  {:1.4e} F'.format(C1p) )
print('El Qoc del capacitor empleado (ESR):')
print('Qoc =  {:1.3f} '.format(Qoc) )
print('rpcp =  {:1.3f} ohms'.format(rpcp) )

print('El Qoc resultante:')
print('QoC =  {:1.3f} '.format(QoC) )
print('rpcs =  {:1.3f} ohms'.format(rpcs) )

print('')
print('L1  =  {:1.4e} Hy'.format(L1) )
print('QoL =  {:1.3f} '.format(QoL) )
print('rpls =  {:1.3f} ohms'.format(rpls) )

print('')
print('Qc  =  {:1.3f} '.format(Qc) )
print('BW  =  {:1.3e} '.format(BW) )
```

# Simulando y calculando potencia sobre la carga

```{python}
# Simulando y verificando el circuito serie con derivación y las perdidas del capacitor
Image(filename= "fig/eje1sim4c.png",width=750)
```

```{python}
# Ahora comparamos con el circuito usando el capacitor sin perdidas
## DATOS
print('Los datos empleados para los calculos:')
print('RL  =  {:1.1f} ohm'.format(RL) )
print('C1 =  {:1.3e} F'.format(C1) )
print('L1  =  {:1.4e} Hy'.format(L1) )
print('rpls  =  {:1.3f} ohm'.format(rpls) )
print('rg  =  {:1.3f} ohm'.format(rg) )
print('vg  =  {:1.3e} Vp'.format(vg) )
print('')

# Capacitor serie 
Xcs  = -1/(w*C1)
Zc   = ESR + 1j*Xcs

# C1 con perdidas en paralelo con RL
ZcRL = RL * Zc / (RL +  Zc)

# inductor serie con perdidas
Xls  = w*L1
ZL   = rpls + 1j*Xls


# Impedancia total incluida la impedancia del generador
Z   = rg + ZL + ZcRL

# Calculo de la potenicia de RL
i   = vg /Z
vrl = i * ZcRL
irl = vrl/RL
Prl = np.abs(irl*vrl)/2 # potenica eficaz

imprimePRL(Prl)
```

```{python}

```

```{python}

```
